### ISSUE TITLE
[BUG]: How to get all request headers

### ISSUE THREAD

**Issue by tientq64** [octokit/rest.js#475]
### What happened?

I need to get the "github-authentication-token-expiration" header, but the header returned by the octokit/rest method only includes this properties, not all the headers:
```js
{
    'cache-control': 'private, max-age=60, s-maxage=60',
    'content-type': 'application/json; charset=utf-8',
    etag: 'W/"4414ed725cbf2c0ae084e5a7c623cfc4799ccdbb24d20e9ed6d03a6ecf53ca59"',
    'last-modified': 'Sat, 23 Nov 2024 05:09:55 GMT',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'D8D6:329CE:2A89F1:301071:674B51F2',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4960',
    'x-ratelimit-reset': '1732990403',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '40'
}
```
All headers:
```yaml
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
cache-control: private, max-age=60, s-maxage=60
content-encoding: gzip
content-security-policy: default-src 'none'
content-type: application/json; charset=utf-8
date: Sat, 23 Nov 2024 05:09:55 GMT
etag: W/"4414ed725cbf2c0ae084e5a7c623cfc4799ccdbb24d20e9ed6d03a6ecf53ca59"
github-authentication-token-expiration: 2025-01-21 00:00:00 +0700
last-modified: Sat, 23 Nov 2024 05:09:55 GMT
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
server: github.com
strict-transport-security: max-age=31536000; includeSubdomains; preload
vary: Accept, Authorization, Cookie, X-GitHub-OTP,Accept-Encoding, Accept, X-Requested-With
x-accepted-github-permissions: contents=read
x-content-type-options: nosniff
x-frame-options: deny
x-github-api-version-selected: 2022-11-28
x-github-media-type: github.v3; format=json
x-github-request-id: D8D6:329CE:2A89F1:301071:674B51F2
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4960
x-ratelimit-reset: 1732990403
x-ratelimit-resource: core
x-ratelimit-used: 40
x-xss-protection: 0
```

### Versions

Octokit.js v20.1.1, Node v20.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
